import argparse
from pathlib import Path

import pandas as pd

from src.compare.analysis import evaluate_pair, collect_files_from_summary
from src.core.utils import parse_gspan_output, load_spminer_pickle

__all__ = ["main"]


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate isomorphism-based accuracy between SPMiner and gSpan")
    parser.add_argument(
        "--summary-csv",
        default="compare/visuals/batch_n40_60_80_k5_8_10_12/visualization_summary.csv",
        help="Summary CSV generated by visualize_mined_subgraphs.py",
    )
    parser.add_argument(
        "--out-csv",
        default="compare/visuals/batch_n40_60_80_k5_8_10_12/isomorphism_accuracy.csv",
        help="Output CSV path for per-(n,k) metrics",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=3,
        help="每组仅使用前 top-k 个模式进行同构准确率计算",
    )
    args = parser.parse_args()

    summary_csv = Path(args.summary_csv)
    out_csv = Path(args.out_csv)

    sp_files, gs_files = collect_files_from_summary(summary_csv)
    keys = sorted(set(sp_files) & set(gs_files))
    if not keys:
        raise RuntimeError("No matched (n, k) file pairs found in summary CSV")

    rows = []
    for n, k in keys:
        sp_path = sp_files[(n, k)]
        gs_path = gs_files[(n, k)]

        sp_graphs = load_spminer_pickle(sp_path)
        gs_graphs = parse_gspan_output(gs_path)

        metrics = evaluate_pair(sp_graphs, gs_graphs, args.top_k)
        row = {
            "graph_size": n,
            "k": k,
            "spminer_file": str(sp_path),
            "gspan_file": str(gs_path),
        }
        row.update(metrics)
        rows.append(row)

    out_csv.parent.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(rows).sort_values(["graph_size", "k"]).reset_index(drop=True)
    df.to_csv(out_csv, index=False)

    macro_acc = float(df["accuracy"].mean())
    weighted_acc = float((df["accuracy"] * df["gspan_count"]).sum() / max(df["gspan_count"].sum(), 1))
    print(f"Saved: {out_csv}")
    print(f"Pairs: {len(df)}")
    print(f"Macro accuracy: {macro_acc:.4f}")
    print(f"Weighted accuracy (by gspan_count): {weighted_acc:.4f}")


if __name__ == "__main__":
    main()
